set shell := ["powershell.exe", "-c"]

exe := "main.exe"
input_file := ".\\main.cpp"
output_file := ".\\main.exe"

build:
  zig cc -o {{exe}} {{input_file}} "-Wl,/subsystem:windows"

run: build
  {{output_file}}

debug: build
  raddbg.exe {{output_file}}
